### ISSUE TITLE
mxnet/lr_scheduler missing

### ISSUE THREAD

**Issue by ljulliar** [mrkn/mxnet.rb#18]
I just updated my local git repo with your latest commits. When i issue a require 'mxnet' I get the following error:
```
> require 'mxnet'
LoadError: cannot load such file -- mxnet/lr_scheduler
	from /big/misc/applications/Ruby/extensions/mxnet/mxnet.rb/lib/mxnet.rb:32:in `require'
```
May you forgot to commit the lr_scheduler file ?

PS: I keep working on spec files

**Comment by ljulliar** [comment]
And same for mxnet/optimizer

**Comment by mrkn** [comment]
I'm sorry for the inconvenience due to my mistake.
I've fixed this issue at the master branch.

**Comment by ljulliar** [comment]
Thank you for fixing this one. I have just fetched the update from upstream. Now mxnet/gluon is also failing :-) You probably forgot it as well
